version: '3.9'

services:
  go_ecom:
    build: ./
    command: ./go_ecom
    ports:
      - 8080:8080
    depends_on:
        db:
          condition: service_healthy
    environment:
      - ENV=dev
      - SERVER_PORT=8080
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=go_ecom_db
      - DB_HOST=db
      - DB_PORT=5432
  db:
    restart: always
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5460:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s